[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "RooAgent"
version = "0.3.0"
description = "Agent For ROOT"
authors = [
    { name="Aman Desai", email="amanmukeshdesai@gmail.com"}
]
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "pandas",
    "numpy",
    "scipy",
    "matplotlib>=3.5",
    "mcp[cli]",
    "typing_extensions",
    "langchain-core",
    "langgraph",
    "langchain-openai",
    "langchain-anthropic",
    # "langchain-ollama",
]

requires-python = ">=3.10"
[project.scripts]
rooagent-mcp = "rooagent.rooagent:main"
rooagent = "rooagent.rooagent:cli_main"

[project.urls]
Homepage = "https://github.com/amanmdesai/RooAgent"

[tool.setuptools.packages.find]
exclude = ["tests", "test*"]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov",
]

[tool.pytest.ini_options]
pythonpath = ["."]
